CREATE TABLE `cst339`.`CUSTOMERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `F_NAME` VARCHAR(45) NULL,
  `L_NAME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `PHONE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));
